events {
    worker_connections 1024;
}

http {
    upstream prediction {
        server prediction-service:8001;
    }

    upstream recommendation {
        server recommendation-service:8002;
    }

    server {
        listen 80;

        # Prediction service
        # Postman: POST http://localhost/api/predict
        location /api/predict {
            proxy_pass http://prediction/predict;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/health {
            proxy_pass http://prediction/health;
            proxy_set_header Host $host;
        }

        # Swagger UI del prediction service
        location /api/docs {
            proxy_pass http://prediction/docs;
            proxy_set_header Host $host;
        }

        # Recommendation service
        # Postman: POST http://localhost/api/recommendations
        location /api/recommendations {
            proxy_pass http://recommendation/recommendations;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Swagger UI del recommendation service
        location /api/recommendations/docs {
            proxy_pass http://recommendation/docs;
            proxy_set_header Host $host;
        }
    }
}