apiVersion: v1
kind: Service
metadata:
  name: recommendation-service
  namespace: mlops
spec:
  selector:
    app: recommendation-service
  ports:
    - port: 8002
      targetPort: 8002
      nodePort: 30802
  type: NodePort
