apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --file docker-compose.yml --out k8s/ --volumes hostPath
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: training-service
  name: training-service
spec:
  ports:
    - name: "8003"
      port: 8003
      targetPort: 8003
  selector:
    io.kompose.service: training-service
