{
 "title": "MLOps Monitoring Dashboard",
 "tags": [
  "mlops",
  "monitoring",
  "drift"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Consumo promedio predicho",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    { "expr": "model_avg_prediction", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Dataset drift",
   "type": "stat",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "dataset_has_drift", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Porcentaje de columnas con drift",
   "type": "stat",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "dataset_drift_share * 100", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total de predicciones del modelo en producción",
   "type": "stat",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "model_predictions_total", "legendFormat": "__auto" }
   ]
  }
 ]
}